version: '3'
services:
  mysql:
    container_name: mysqlContainer
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=foodDivvy
    ports:
      - '3306:3006'